# Generated by Django 3.2.7 on 2021-09-02 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=50, verbose_name='参加者名')),
                ('participant_mail', models.EmailField(max_length=50, verbose_name='参加者メールアドレス')),
                ('enthusiasm', models.TextField(max_length=200, verbose_name='意気込み')),
                ('participate_product_id', models.IntegerField(verbose_name='参加プロダクトid')),
                ('participate_date', models.DateField(default=django.utils.timezone.now, verbose_name='参加日')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_name', models.CharField(max_length=50, verbose_name='投稿者名')),
                ('poster_mail', models.EmailField(max_length=50, verbose_name='投稿者メールアドレス')),
                ('product_name', models.CharField(max_length=50, verbose_name='プロダクト名')),
                ('hackathon_date', models.DateField(verbose_name='ハッカソン開催日')),
                ('recluting_headcount', models.IntegerField(verbose_name='募集人数')),
                ('delete_key', models.CharField(max_length=8, verbose_name='削除キー')),
                ('product_brief', models.TextField(max_length=500, verbose_name='プロダクト概要')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='説明資料')),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('post_delete_date', models.DateTimeField(blank=True, verbose_name='投稿削除日')),
            ],
        ),
    ]
