# Generated by Django 3.2.7 on 2021-09-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonguild', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='webhookURL',
            field=models.TextField(max_length=100, null=True, verbose_name='投稿者slackwebhookURL'),
        ),
    ]
