# Generated by Django 3.2.7 on 2021-09-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonguild', '0004_auto_20210904_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
