# Generated by Django 3.2.7 on 2021-09-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonguild', '0002_post_webhookurl'),
        ('hackathonguild', '0005_delete_token'),
    ]

    operations = [
    ]
