# Generated by Django 3.2.7 on 2021-09-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonguild', '0006_merge_0002_post_webhookurl_0005_delete_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='enthusiasm',
            field=models.TextField(blank=True, max_length=200, verbose_name='意気込み'),
        ),
        migrations.AlterField(
            model_name='post',
            name='product_brief',
            field=models.TextField(blank=True, max_length=500, verbose_name='プロダクト概要'),
        ),
    ]
