# Generated by Django 3.2.7 on 2021-09-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonguild', '0007_auto_20210905_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='joining_headcount',
            field=models.ImageField(default=0, upload_to='', verbose_name='参加人数'),
        ),
    ]
