# Generated by Django 3.2.7 on 2021-09-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonguild', '0008_post_joining_headcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='joining_headcount',
            field=models.IntegerField(default=0, verbose_name='参加人数'),
        ),
    ]
