# Generated by Django 3.2.7 on 2021-09-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonguild', '0009_alter_post_joining_headcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='delete_key',
            new_name='edit_key',
        ),
    ]
